name = "VibrationalAnalysis"
uuid = "04082e5c-1d57-4577-9a0f-61e6cd56dade"
authors = ["Josef M. Gallmetzer"]
version = "0.1.0"

[deps]
DelimitedFiles = "8bb1440f-4735-579b-a4ab-409b98df4dab"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
